### ISSUE TITLE
Milestones, Todos.

### ISSUE THREAD

**Issue by terrencetec** [terrencetec/seibot#1]
### Deadline: March 1st, 2024

**Deliverables**
- [ ] A Guardian node that does the following:
  - [ ] Grabs seismic noise data
  - [ ] Use seismic noise data, known seismic noise data, plants, controllers, and all available sets of sensor correction filters and blends to forecast future control performance.
  - [ ] Select the best combination from the available pool and use sensor correction and blend fader to switch to that configuration.
- [ ] Test results using HAM7, HAM8 and the filter cavity.
  - [ ] Shape seismic noise injection filters into HAM7 and HAM8.
  - [ ] Comparisons against the usual filters. (Do multiple measurements multiple days)
  - [ ] If we don't have enough time, don't use guardian switching and just do the multiple filters comparisons.

**Tasks**
*Easy stuff*
- [ ] Make a guardian
- [ ] Code that grabs filters from Foton files and converts them into Python accessible format like `control.TransferFunction`
- [ ] Code that collects noises, plants, and controllers and put them into usable format.
- [ ] Code that evaluates a certain cost function.
- [ ] Code that reads `.ini` configuration files, which specifies things, like the cost function, frequency of operation, etc.

*Hard stuff*
- [ ] Gather multiple seismic noise spectrums from selected times (lock losses, earthquakes, seasonal changes, etc)
- [ ] Separate them into training and test datasets. Test datasets are used to shape injection filters.
- [ ] Optimize sensor correction filters and blends according to training datasets.
- [ ] Show the inefficiency of a static filter filter.
