### ISSUE TITLE
GUI TODO list

### ISSUE THREAD

**Issue by terrencetec** [terrencetec/seibot#4]
- [ ] Make post_plant optional.
- [x] Make new foton files with new filters
- [x] Make new estimation methods
- [x] Make new seismic and post plant models.
- [x] Make new inertial sensor models.
- [x] Add GUI title
- [x] Test GUI and compare estimation with witness measurements. 
- [x] Dynamically adjust alpha
- [x] Fix witness zorder
- [x] Fix witness calibration

**Comment by terrencetec** [comment]
interp1d will not work at high frequency for missing data.
